
---


# =============================================================================
# Options
# =============================================================================

options:

    mode: development
    live:
        enabled: false
        port: 3000
        root: public
        watchPaths:
            - src/**
            - config/**
        ignoredPaths:
            - node_modules/**
    logLevel: debug


# =============================================================================
# Stages
# =============================================================================

stages:

    # Preprocessing
    # =========================================================================
    -
        name: Preprocessing
        description: "Before starting a new build."

        steps:

            # Dirs Clean
            # -----------------------------------------------------------------
            -
                name: CleanBuildDirStep
                action: DirectoryCleanAction
                options:
                    dirPath: "./dist"

            # Dirs Clean
            # -----------------------------------------------------------------
            -   name: ProcessMainStyles
                action: StyleProcessingAction
                options:
                    inputFile: "./src/scss/index.scss"
                    outputFile: "./dist/css/unit.gl.min.css"
                    styleOption: "compressed"
            -
                name: ProcessAdditionalStyles
                action: StyleProcessingAction
                options:
                    inputFile: "./src/scss/index.scss"
                    outputFile: "./dist/css/unit.gl.css"
                    styleOption: "expanded"

            # Copy Files
            # -----------------------------------------------------------------
            -
                name: CopyLICENSE
                action: FileCopyAction
                options:
                    srcFile: "./LICENSE"
                    destDir: "./dist"
            -
                name: CopyREADME
                action: FileCopyAction
                options:
                    srcFile: "./README.md"
                    destDir: "./dist"

            # Copy Dirs
            # -----------------------------------------------------------------
            -
                name: CopySrcSCSS
                action: DirectoryCopyAction
                options:
                    srcDir: "./src/scss"
                    destDir: "./dist/scss"
            -
                name: CopySrcTS
                action: DirectoryCopyAction
                options:
                    srcDir: "./src/ts"
                    destDir: "./dist/ts"

            # Compile TS to JS
            # -----------------------------------------------------------------

            # -
            #     name: Compile TS to JS
            #     action: TypeScriptCompilerAction
            #     options:
            #         tsConfigPath: "./tsconfig.json"
            #         filePaths:
            #             - "src/ts/index.ts"
            #             # - "src/utils.ts"
            #         outputDir: "./dist/js"
            #         compilerOptions:
            #             target: "ES2020"
            #             module: "CommonJS"

            # Package.json
            # -----------------------------------------------------------------
            -
                name: Package.json
                action: PackageManagerAction
                options:
                    packageJsonPath: "./package.json"
                    outputDir: "./dist"
                    fields:
                        - name
                        - version
                        - bin
                        - dependencies
                        - description
                        - keywords
                        - license
                        - homepage
                        - author
                        - contributors
                        - repository
                        - funding
                        - exports
                    # customConfig:
                    #     private: true
                    #     scripts:
                    #     start: "node index.js"
                    #     build: "npm run build"
                    #     devDependencies:
                    #     typescript: "^5.0.0"

            # Replace Version
            # -----------------------------------------------------------------
            -
                name: ReplaceVersion
                action: VersionWriteAction
                options:
                    files:
                    -   path: "./CITATION.cff"
                        key: "version: "
                    -   path: "./VERSION"
                        # key: ""
