
---


# =============================================================================
# Options
# =============================================================================

options:

    mode: development
    live:
        enabled: false
        port: 3000
        root: public
        watchPaths:
            - src/**
            - config/**
        ignoredPaths:
            - node_modules/**
    logLevel: debug


# =============================================================================
# Stages
# =============================================================================

stages:

    # Preprocessing
    # =========================================================================
    -
        name: Preprocessing
        description: "Before starting a new build."

        steps:

            # Dirs Clean
            # -----------------------------------------------------------------
            -
                name: CleanBuildDirStep
                action: DirectoryCleanAction
                options:
                    dirPath: "./dist"  # Path to the directory to be cleaned

            # Dirs Clean
            # -----------------------------------------------------------------
            -   name: ProcessMainStyles
                action: StyleProcessingAction
                options:
                    inputFile: "./src/scss/index.scss"
                    outputFile: "./dist/styles/main.css"
                    styleOption: "compressed"
            -
                name: ProcessAdditionalStyles
                action: StyleProcessingAction
                options:
                    inputFile: "./src/scss/index.scss"
                    outputFile: "./dist/styles/additional.css"
                    styleOption: "expanded"

            # Copy Files
            # -----------------------------------------------------------------
            -
                name: CopyLICENSE
                action: FileCopyAction
                options:
                    srcFile: "./LICENSE"
                    destDir: "./dist"
            -
                name: CopyREADME
                action: FileCopyAction
                options:
                    srcFile: "./README.md"
                    destDir: "./dist"

            # Copy Dirs
            # -----------------------------------------------------------------
            -
                name: CopySrcSCSS
                action: DirectoryCopyAction
                options:
                    srcDir: "./src/scss"
                    destDir: "./dist/scss"
            -
                name: CopySrcTS
                action: DirectoryCopyAction
                options:
                    srcDir: "./src/ts"
                    destDir: "./dist/ts"

            # Package.json
            # -----------------------------------------------------------------
            -
                name: Package.json
                action: PackageManagerAction
                options:
                    # Path to the existing package.json file to read
                    packageJsonPath: "./package.json" # not going well
                    outputDir: "./dist"

            # Replace Version
            # -----------------------------------------------------------------
            -
                name: ReplaceVersion
                action: VersionWriteAction
                options:
                    files:
                    -   path: "./CITATION.cff"
                        key: "version: "
                    -   path: "./VERSION"
                        key: "v"
